### ISSUE TITLE
not an issue - question regarding flashing forward apfs checkpoint

### ISSUE THREAD

**Issue by johndpope** [ydkhatri/APFS_010#2]
according to this article, researchers were able to rewind to a previous checkpoint 
http://www.sciencedirect.com/science/article/pii/S1742287617301408

it's my understanding you can do this on an apfs drive with time machine. 
It is my hope that I can dd an image / rewind to a previous checkpoint and then find out the mechancies / which bytes changed - then use this to recover a failed drive of mine.

related issue here
https://github.com/cugu/afro/issues/2

did you try this? I read your front title mentioning it's hard to visualise sectors with python so you built this. I was thinking of doing a swift app using kaitai 
https://github.com/kaitai-io/kaitai_struct_swift_runtime/pull/2
and cherry picking this code to wrap around the base in swift
https://github.com/cugu/afro/tree/master/afro/libapfs

**Comment by ydkhatri** [comment]
I suggest you create a dd image and try to run the Python code (afro) first
to see if it recovers any data. It is designed for that specific purpose.

Can you also elaborate on how exactly your drive failed?

**Comment by johndpope** [comment]
I was using usb3 to boot off external 1TB ssd / macOS majove etc. worked really well. 
Ssd is fine. Just logic problem. I ejected the cable from USB port / then plugged it back in / on a port on opposite side of computer. Rebooted to find it couldn’t recognize drive. 
Surprisingly I had gotten away with re attaching drive to same port before. But won’t ever take that  risk again.  OS X should know better and self destruct/reboot on detaching.

**Comment by johndpope** [comment]
fyi - there was an update to  apfs.fsk 
https://github.com/ydkhatri/APFS_010/blob/master/apfs.010.bt#L455
